---
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
        dependency_name: "rails_warden"
      - match:
        dependency_name: "omniauth"
      - match:
        dependency_name: "omniauth-zendesk-oauth2"
      - match:
        dependency_name: "bootstrap-sass"
      - match:
        dependency_name: "sidekiq"
      - match:
        dependency_name: "dotenv-rails"
      - match:
        dependency_name: "byebug"
      - match:
        dependency_name: "rollbar"
      - match:
        dependency_name: "puma"
